# DATASOURCE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ProjetoAcademy
spring.datasource.username=postgres
spring.datasource.password=phfa1996
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SERVER
server.port=8080

# Configurar recurso estático para servir arquivos enviados
# Observação: estamos salvando em ./uploads e mapeando /uploads/** para este diretório
spring.web.resources.static-locations=file:uploads/,classpath:/static/

# SPRING MVC - Garantir que controllers REST tenham prioridade
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/